AlexandrShcherbakov/etna

- .gitignore
- CMakeLists.txt
- etna/CMakeLists.txt
- etna/include/etna/UniqueImage.hpp
- etna/source/UniqueImage.cpp
- etna/source/VmaImplementation.cpp
- get_cpm.cmake
- thirdparty.cmake
Basic public include and private sources structure which is standard for librareis. Users shall include our headers as `<etna/UniqueImage.hpp>`.
Linked vulkan library to `etna` target.
Also added auto-download of CmakeCPM, which allows us to automagically fetch dependencies, such as VulkanMemoryAllocators and StbImage. Added those as well.
Sadly, as stb libraries and VMA do not provide proper cmake, targets had to be added manually in thirdparty.cmake. Libraries which provide proper modern (no more than 10 year old) cmakelists get integrated in a single line.
> Added basic project structure

- .gitignore
- etna/CMakeLists.txt
- etna/include/etna/Assert.hpp
- etna/include/etna/Buffer.hpp
- etna/include/etna/DescriptorSet.hpp
- etna/include/etna/DescriptorSetLayout.hpp
- etna/include/etna/Etna.hpp
- etna/include/etna/EtnaConfig.hpp
- etna/include/etna/Forward.hpp
- etna/include/etna/GlobalContext.hpp
- etna/include/etna/GraphicsPipeline.hpp
- etna/include/etna/Image.hpp
- etna/include/etna/PipelineBase.hpp
- etna/include/etna/PipelineManager.hpp
- etna/include/etna/ShaderProgram.hpp
- etna/include/etna/VertexInput.hpp
- etna/include/etna/Vulkan.hpp
- etna/source/Etna.cpp
- etna/source/GlobalContext.cpp
- etna/source/GraphicsPipeline.cpp
- etna/source/PipelineBase.cpp
- etna/source/PipelineManager.cpp
The design is as follows:
We have a pipeline manager that stores creation info for all pipelines ever created, as well as the actual `vk::UniquePipeline`s. Pipeline objects themselves are thin handles that get their data from the manager. This allows the manager to recreate underlying vulkan pipelines when shaders are reloaded, while the user still has an illusion of pipelines being unique objects.
The arguments for creating a graphics pipelines are custom-made structures that allocate arrays on the heap like there's no tomorrow, but allow for pretty initialization code and sensible defaults for most use cases. Only two things need to be always specified: vertex shader input (model format) and fragment shader output (attachment formats). The vertex input parameter is decomposed in a …
> Implemented etna pipelines

- etna/source/PipelineManager.cpp
Destroyed pipelines would get recreated when shaders are reloaded, oops
> Fixed small bug with destroying pipelines

- etna/source/GlobalContext.cpp
I thought that it will be on by default, but it turns out that we need to explicitly enable it.
This layer implements sync2 API functions using sync1 calls, but only when native sync2 is not supported by the driver. Allows people with lazy GPU driver vendors to use etna. Sync2 is almost 2 years old btw :)
> Turned on sync2 -> sync1 translation layer

- etna/include/etna/Buffer.hpp
- etna/include/etna/Image.hpp
- etna/include/etna/Sampler.hpp
- etna/source/Buffer.cpp
- etna/source/Image.cpp
- etna/source/Sampler.cpp
* Use `vk::UniqueXxx` instead of `vk::Xxx` to simplify code
* Assert with informative messages instead of throwing exceptions that will never be caught anywhere anyway
* Fixed a crash when assigning to a mapped buffer
* Unify Image and Buffer: both implement rule of 3 using `swap` and `reset` to avoid copypasta
> Etna wrappers cleanup

- etna/include/etna/ComputePipeline.hpp
- etna/include/etna/PipelineManager.hpp
- etna/source/PipelineManager.cpp
Currently supported addition for computePipeline like this:
`m_cullingPipeline      = pipelineManager.createComputePipeline("culling", {});`
I'm not sure if it works correctly, but for current state I have no validation errors on the stage of creation computePipeline.
> Add ComputePipeline

- etna/source/PipelineManager.cpp
Fixed ETNA_ASSERT to ETNA_ASSERTF, now it builds. Also %d -> {}
> fixed ETNA_ASSERT

- etna/source/PipelineManager.cpp
My previous changes to dynamic states were causing validation errors now that viewportCount and scissorCount are not 0.
> Return normal viewport and scissor dynamic states

- etna/include/etna/Etna.hpp
- etna/source/Etna.cpp
- etna/source/PipelineManager.cpp
Right now resource barriers are not automatically flushed before compute shader dispatch like happens with graphical pipelines, so this function allows for correct usage of etna::set_state with compute pipeline resources
> Added flush_barriers function to Etna.hpp

- etna/include/etna/RenderTargetStates.hpp
- etna/source/RenderTargetStates.cpp
Added loadOp, storeOp and clear values to AttachmentParams.
New usage with optional params:
```
etna::RenderTargetState::AttachmentParams colorAttachmentParams{a_targetImage, a_targetImageView};
colorAttachmentParams.loadOp = vk::AttachmentLoadOp::eDontCare;
colorAttachmentParams.storeOp = vk::AttachmentStoreOp::eStore;
etna::RenderTargetState renderTargets(a_cmdBuff, {m_width, m_height}, {colorAttachmentParams}, {});
```
> Added more fields to AttachmentParams

- etna/include/etna/Etna.hpp
- etna/source/Etna.cpp
Usage:
```
etna::Image image = etna::create_image_from_bytes(etna::Image::CreateInfo
{
.extent = vk::Extent3D{4, 4, 1},
.name = "my_image",
.format = vk::Format::eR32G32B32A32Sfloat,
.imageUsage = vk::ImageUsageFlagBits::eSampled
}, m_cmdBufferAux, bytes.data());
```
> Added ability to create images from bytes

- etna/include/etna/Image.hpp
Обход бага gcc и clang https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88165, из-за которого etna отказывается собираться
> gcc bug 88165 bypass

- etna/include/etna/RenderTargetStates.hpp
- etna/source/RenderTargetStates.cpp
- Remade RenderTargetState constructor to take Rect2D instead of Extent2D to enable debug drawing to part of the framebuffer.
- Added new constructor to RenderTargetState::AttachmentParams to allow drawing without clearing image, also for debug rendering.
> Remade RenderTargetState constructor to take Rect2D instead of Ext2D 

- etna/include/etna/RenderTargetStates.hpp
- etna/source/RenderTargetStates.cpp
- etna/source/StateTracking.cpp
- etna/source/StateTracking.hpp
1. Stencil attachment для rendertarget'а.
2.  Барьеры для использования depth и/или stencil. 
3. 3 if'а в конструкторе для возможности использовать либо весь VK_FORMAT_Dxx_SFLOAT_S8_UINT, либо только его depth или stencil часть, либо части от разных изображений (последнее само собой вышло, вряд ли так кто-то будет делать)
> Rendertarget features

- etna/include/etna/RenderTargetStates.hpp
- etna/source/RenderTargetStates.cpp
- etna/source/StateTracking.cpp
- etna/source/StateTracking.hpp
+3 поля в attachment
+2 соответствующих конструктора для attachment
+1 барьер для resolve изображения перед отрисовкой (обратный барьер на совести пользователя)
> Render target state resolve

- etna/include/etna/RenderTargetStates.hpp
- etna/source/RenderTargetStates.cpp
- etna/source/StateTracking.cpp
- etna/source/StateTracking.hpp
Опциональные поля vk::ImageAspectFlags нужны для depthStencil изображений. Если изображение имеет и глубину, и трафарет, но мы хотим использовать что-то одно в проходе. то надо либо включать раздельные барьеры, либо указать дополнительное поле imageAspect = eDepth | eStencil
> barrier fixes

- etna/include/etna/Etna.hpp
- etna/include/etna/EtnaConfig.hpp
- etna/include/etna/Vulkan.hpp
- etna/source/DebugUtils.cpp
- etna/source/GlobalContext.cpp
- Add support for MacOS (via MoltenVK).
- Add more extensive validation option (see [VkValidationFeatureEnableEXT](https://registry.khronos.org/VulkanSC/specs/1.0-extensions/man/html/VkValidationFeatureEnableEXT.html)) enabling:
- VK_VALIDATION_FEATURE_ENABLE_GPU_ASSISTED_EXT: "specifies that GPU-assisted validation is enabled. Activating this feature instruments shader programs to generate additional diagnostic data"
- VK_VALIDATION_FEATURE_ENABLE_BEST_PRACTICES_EXT: "specifies that Vulkan best-practices validation is enabled. Activating this feature enables the output of warnings related to common misuse of the API, but which are not explicitly prohibited by the specification"
- VK_VALIDATION_FEATURE_ENABLE_SYNCHRONIZATION_VALIDATION_EXT: "specifies that Vulkan synchronization …
> Add MacOS support and improve validation initialization

- etna/include/etna/BarrierBehavoir.hpp
- etna/include/etna/DescriptorSet.hpp
- etna/include/etna/Etna.hpp
- etna/include/etna/GlobalContext.hpp
- etna/include/etna/RenderTargetStates.hpp
- etna/source/DescriptorSet.cpp
- etna/source/Etna.cpp
- etna/source/GlobalContext.cpp
- etna/source/RenderTargetStates.cpp
- etna/source/StateTracking.cpp
- etna/source/StateTracking.hpp
Добавил опцию подавить создание барьеров при вызове createDescriptorSet. Дефолтное поведение createDescriptorSet создаёт кучу проблем, которые нетривиально разрешить, а автоматическая генерация барьеров зачастую создаёт лишние зависимости
> Опция подавить создание барьеров при вызове createDescriptorSet

- .github/workflows/lint.yaml
- .gitignore
- CMakeLists.txt
- etna/CMakeLists.txt
- etna/include/etna/Buffer.hpp
- etna/include/etna/DescriptorSetLayout.hpp
- etna/include/etna/Etna.hpp
- etna/include/etna/EtnaConfig.hpp
- etna/include/etna/EtnaEngineConfig.hpp.in
- etna/include/etna/Image.hpp
- etna/include/etna/RenderTargetStates.hpp
- etna/source/GlobalContext.cpp
- etna/source/StateTracking.cpp
- get_version.cmake
Changes:
- use cpp wrapper for (almost) all constants
Also deprecated VK_EXT_calibrated_timestamps was
replaced by VK_KHR_calibrated_timestamps.
See https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_calibrated_timestamps.html#_promotion_to_vk_khr_calibrated_timestamps
And deprecated VK_MAKE_VERSION was replaced by vk::makeApiVersion
(thanks to Khronos for this very important change)
- add versioning based on git tags
- lint update: bump vulkan sdk to 1.3.296 and ubuntu to 24.04
> minor refactoring

- etna/source/DescriptorSet.cpp
trivial solution for (one of) the RAW hazard in graphics course TODO: maybe we should add overload for bindings with
the same params as for set_state()?
> add another missed access flag for DescriptorSet creation

- .github/workflows/comment-lint-results.yaml
- .github/workflows/linux.yaml
- .github/workflows/windows.yaml
- updated VulkanSDK for linux and win to same version as lint
- updated clang-tidy-review/post (idk how it worked until today)
> bump some workflow repos

- etna/include/etna/BindingItems.hpp
- etna/include/etna/DescriptorSet.hpp
- etna/include/etna/Etna.hpp
- etna/include/etna/GlobalContext.hpp
- etna/include/etna/Sampler.hpp
- etna/source/DescriptorSet.cpp
- etna/source/Etna.cpp
- etna/source/GlobalContext.cpp
- etna/source/Sampler.cpp
… bindless
1) Added PersitsendDescriptorSet class. It is a lighter version of
DescriptorSet without generation data, command buffer refererence or
automatic set_states. This is suited for dsets created once and alive
for the duration of the program, i.e. bindless.
2) Added PersistentDescriptorPool to allocate such sets -- this pool is
not multiplexed for frames in flight and never deallocates -- the
only way to free dsets allocated from it is nuking the whole pool
(and it lives in the context, so it's lifetime is the whole program).
3) Added create_persistent_descriptor_set free function to create such
sets from the pool in the context.
This allowed me to implement bindless without pulling etna's guts out into my code.
> Added PersistentDescriptorPool and PersitsendDescriptorSet to support bindless

- etna/include/etna/DescriptorSet.hpp
- etna/include/etna/DescriptorSetLayout.hpp
- etna/source/DescriptorSet.cpp
- etna/source/DescriptorSetLayout.cpp
- thirdparty.cmake
This PR adds support for unsized dynamic arrays in etna.
1. When we parse reflection info into a descriptor set layout, we now handle the case when dimensions are SPV_REFLECT_ARRAY_DIM_RUNTIME (i. e. 0). In this case, we set a special flag on DescriptorSetInfo (hasDynDescriptorArray) that indicates that this dset has a bindless array. This is only allowed for the last used binding in the set -- if it is not the last, we validate it (we also validate in on merging infos now)
2. Now in DescriptorSetInfo we store binding flags along with bindings themselves. They are not tweakable to the user, however for the dynamic array we set 'partial write' and 'variable count' flags. These flags are applied on dset layout creation. For variable dset count we set cap equal to the pool size for this dset …
> Proper bindless support + cmake fix
